{{- if and .Values.initdb.enabled .Values.initdb.createUuidOssp }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "postgres.fullname" . }}-initdb
  labels:
    {{- include "postgres.labels" . | nindent 4 }}
data:
  01-init.sql: |
    CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
{{- end }}
