apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "muffin-wallet.fullname" . }}
  labels:
    {{- include "muffin-wallet.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "muffin-wallet.labels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "muffin-wallet.labels" . | nindent 8 }}
    spec:
      containers:
        - name: muffin-wallet
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
          env:
            - name: SPRING_DATASOURCE_URL
              value: {{ .Values.env.SPRING_DATASOURCE_URL | quote }}
            - name: SPRING_DATASOURCE_USERNAME
              value: {{ .Values.env.SPRING_DATASOURCE_USERNAME | quote }}
            - name: SPRING_DATASOURCE_PASSWORD
              value: {{ .Values.env.SPRING_DATASOURCE_PASSWORD | quote }}
          readinessProbe:
            httpGet:
              path: {{ .Values.probes.readinessPath | quote }}
              port: {{ .Values.service.port }}
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: {{ .Values.probes.livenessPath | quote }}
              port: {{ .Values.service.port }}
            initialDelaySeconds: 20
            periodSeconds: 10
