{
 "title": "Hw_dashboards",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "app",
    "label": "app",
    "query": {}
   },
   {
    "name": "level",
    "label": "Level",
    "query": {}
   },
   {
    "name": "trace",
    "label": "Trace",
    "query": "6983efb97c865600afdce560145afd27"
   }
  ]
 },
 "panels": [
  {
   "title": "Logs count (range)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({app=~\"$app\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Logs by traceId",
   "type": "logs",
   "gridPos": { "h": 12, "w": 11, "x": 13, "y": 0 },
   "targets": [
    {
     "expr": "{app=~\"$app\"} \r\n|~ \"\\\"traceId\\\":\\\"$trace\\\"|\\\"trace_id\\\":\\\"$trace\\\"\"\r\n| json"
    }
   ]
  },
  {
   "title": "Logs ($app)",
   "type": "table",
   "gridPos": { "h": 12, "w": 13, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "{app=~\"$app\", level=~\"$level\"} | json"
    }
   ]
  },
  {
   "title": "WARN+ERROR rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 13, "y": 12 },
   "targets": [
    {
     "expr": "sum(count_over_time({app=~\"$app\", level=~\"ERROR|WARN\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "Trace: $trace",
   "type": "traces",
   "gridPos": { "h": 9, "w": 13, "x": 0, "y": 15 },
   "targets": [
    {
     "filters": [
      {
       "id": "2ccb866d",
       "operator": "=",
       "scope": "span",
       "value": []
      },
      {
       "id": "service-name",
       "operator": "=",
       "scope": "resource",
       "tag": "service.name",
       "value": [ "$app" ],
       "valueType": "string"
      }
     ],
     "limit": 20,
     "linkedQuery": { "expr": "", "refId": "linked" },
     "query": "$trace",
     "tableType": "traces"
    }
   ]
  }
 ]
}