replicaCount: 1

image:
  repository: gendalf1231/muffin-wallet
  tag: "v1.0.4"
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 8085
  targetPort: 8080

env:
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres:5432/walletdb"
  SPRING_DATASOURCE_USERNAME: "wallet"
  SPRING_DATASOURCE_PASSWORD: "walletpass"


probes:
  readinessPath: "/actuator/health"
  livenessPath: "/actuator/health"

logs:
  enabled: true
  mountPath: /logs
  pvc:
    size: 1Gi
    storageClassName: ""

tracing:
  zipkinEndpoint: "http://tempo.observability.svc.cluster.local:9411/api/v2/spans"

promtail:
  enabled: true
  image:
    repository: grafana/promtail
    tag: "2.9.7"
    pullPolicy: IfNotPresent
  clientUrl: "http://loki.observability.svc.cluster.local:3100/loki/api/v1/push"

