apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "muffin-currency.fullname" . }}
  labels:
    {{- include "muffin-currency.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "muffin-currency.labels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "muffin-currency.labels" . | nindent 8 }}
    spec:
      containers:
        - name: muffin-currency
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}

          readinessProbe:
            httpGet:
              path: /readyz
              port: {{ .Values.service.targetPort }}

          livenessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.service.targetPort }}

