apiVersion: v1
kind: ConfigMap
metadata:
  name: tempo-config
  namespace: observability
data:
  tempo.yaml: |
    server:
      http_listen_port: 3200

    distributor:
      receivers:
        zipkin:
          endpoint: 0.0.0.0:9411

    ingester:
      lifecycler:
        ring:
          kvstore:
            store: inmemory
          replication_factor: 1

    storage:
      trace:
        backend: local
        local:
          path: /var/tempo/traces

    compactor:
      compaction:
        block_retention: 168h
